name: Publish
on:
  push:
    tags:
      - v*.*.*
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout SharpHound
        uses: actions/checkout@v4
        with:
          repository: BloodHoundAD/SharpHound
          path: SharpHound
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.0.x
      - name: Build SharpHound
        run: |
          cd SharpHound
          dotnet restore .
          dotnet build -c Release
      - name: Zip
        # https://michael-mckenna.com/how-to-upload-file-to-github-release-in-a-workflow/
        run: |
          dir
          7z a -tzip -mx9 $PWD/SharpHound.zip $PWD/SharpHound/bin/Release/net462/*
          dir
          gh release upload ${{github.event.release.tag_name}} $PWD/SharpHound.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
      #- name: Upload to Release
        #uses: softprops/action-gh-release@v2
        #with:
          #files: D:\a\jubilant-octo-lamp\jubilant-octo-lamp/SharpHound.zip
